"""Pre-build script for PlatformIO: bump a build counter and generate src/build_info.h

This script reads `data/config.json` `fw_version` as a base (expects `vMAJOR.MINOR` or
`vMAJOR.MINOR.PATCH`), increments a local `.build_count` file, and writes `src/build_info.h`
with FW_VERSION set to `vMAJOR.MINOR.BUILD`.

It is safe to run repeatedly; `.build_count` is stored in the project root (not committed by
default) so builds increment the build number without modifying tracked source files.
"""
import os
import json
import re

project_dir = os.getcwd()
data_config = os.path.join(project_dir, 'data', 'config.json')
build_count_file = os.path.join(project_dir, '.build_count')
build_info_h = os.path.join(project_dir, 'src', 'build_info.h')

def read_fw_base():
    try:
        with open(data_config, 'r', encoding='utf-8') as f:
            doc = json.load(f)
            fw = doc.get('fw_version', '')
            return fw
    except Exception:
        return ''

def parse_base(fw):
    # match vMAJOR.MINOR(.PATCH)?
    m = re.match(r'v(\d+)\.(\d+)(?:\.(\d+))?', fw)
    if m:
        major = int(m.group(1))
        minor = int(m.group(2))
        return major, minor
    return 1, 0

def read_build_count():
    if not os.path.exists(build_count_file):
        return 0
    try:
        with open(build_count_file, 'r', encoding='utf-8') as f:
            return int(f.read().strip() or '0')
    except Exception:
        return 0

def write_build_count(n):
    with open(build_count_file, 'w', encoding='utf-8') as f:
        f.write(str(n))

def write_build_info(major, minor, build):
    version = f'v{major}.{minor}.{build}'
    content = f"""// This file is generated by scripts/bump_build.py - do not edit
#pragma once
#define FW_VERSION \"{version}\"
#define FW_BASE_VERSION \"v{major}.{minor}\"
#define FW_BUILD_NUMBER {build}
"""
    with open(build_info_h, 'w', encoding='utf-8') as f:
        f.write(content)
    print(f'Generated {build_info_h} with FW_VERSION={version}')
    # Write a generated data/build_info.json so builds don't modify tracked files
    try:
        build_info_path = os.path.join(project_dir, 'data', 'build_info.json')
        build_doc = {
            'fw_version': version,
            'fw_base': f'v{major}.{minor}',
            'build': build
        }
        with open(build_info_path, 'w', encoding='utf-8') as f:
            json.dump(build_doc, f, indent=4)
        print(f'Wrote {build_info_path}')
    except Exception as e:
        print(f'Warning: failed to write data/build_info.json: {e}')

def main():
    fw = read_fw_base()
    major, minor = parse_base(fw)
    count = read_build_count()
    count += 1
    write_build_count(count)
    write_build_info(major, minor, count)

if __name__ == '__main__':
    main()
