name: Build firmware on src changes

on:
  push:
    paths:
      - 'src/**'
      - 'platformio.ini'
  pull_request:
    paths:
      - 'src/**'
      - 'platformio.ini'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Cache PlatformIO packages
        uses: actions/cache@v4
        with:
          path: ~/.platformio/packages
          key: ${{ runner.os }}-platformio-packages-${{ hashFiles('**/platformio.ini') }}
          restore-keys: |
            ${{ runner.os }}-platformio-packages-

      - name: Install PlatformIO
        run: |
          python -m pip install --upgrade pip
          pip install platformio

      - name: Run PlatformIO build
        run: |
          python -m platformio run
