name: LittleFS sync check

on:
  push:
    paths:
      - 'data/**'
      - '.littlefs_hash'
  pull_request:
    paths:
      - 'data/**'
      - '.littlefs_hash'

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Run LittleFS sync check
        run: |
          python scripts/check_littlefs_sync.py || (echo "LittleFS data out of sync: update .littlefs_hash or run uploadfs" && exit 1)
