name: Validate config.json

on:
  push:
    paths:
      - 'data/config.json'
  pull_request:
    paths:
      - 'data/config.json'

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
      - name: Validate src/build_info.h
        run: |
          python scripts/validate_config.py
      - name: Verify src/build_info.h (generator check)
        run: |
          python scripts/generate_build_info.py
      - name: Show generated file
        run: |
          cat src/build_info.h
